### ISSUE TITLE
[💡FEATURE REQUEST]: Add HTTP Cache Middleware [IMPLEMENTATION TRACKING TICKET]

### ISSUE THREAD

**Issue by alexander-schranz** [spiral/roadrunner-plugins#66]
**Is your feature request related to a problem? Please describe.**

Roadrunner is already handling SSL, as a replace for load balancer, nginx, or other similar service. It would be nice to support a kinde of HTTP Cache, so things like Varnish (which don't support ssl) could be handled

**Describe the solution you'd like**

HTTP Cache Handling could be added as kind of middleware I think. It could be implemented in different Steps and so not all type of caching need to be added as once.

- [ ] **Level 1: HttpCache** over `Cache-Control` and `Vary` Header build on top of `public` and `s-maxage` attributes for `GET` and `HEAD` requests [Http Specification](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2.2.9). Added: The  [`Age`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age) response header when loaded from the cache should correctly be set. Issue: https://github.com/spiral/roadrunner-plugins/issues/187
- [ ] **Level 2: PURGE** request to invalidate the cache based [Varnish Purge](https://varnish-cache.org/docs/trunk/users-guide/purging.html#http-purging) configuration which IPs are allowed to purge.
- [ ] **Level 3: Custom TTL Header** for cache lifetime instead of s-maxage widely used `X-Reverse-Proxy-TTL` (Symfony FOSHTTpCache [CustomTtlListener](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/SymfonyCache/CustomTtlListener.php). This header value is used then instead of `s-maxage` how long the response is cached. [FOS Custom TTL Docs](https://foshttpcache.readthedocs.io/en/latest/symfony-cache-configuration.html#custom-ttl)
- [ ] **Level 4: BAN** BAN request with regex [Varnish BAN](https://varnish-cache.org/docs/trunk/users-guide/purging.html#bans)
- [ ] **Level 5: Tag Based Caching**. Response tag by `X-Cache` header and with invalidation also by Tags [Varnish Key](https://docs.varnish-software.com/varnish-cache-plus/vmods/ykey/)
- [ ] **Level 6: ESI / Edge side includes**  (https://en.wikipedia.org/wiki/Edge_Side_Includes) allows to not cache or cache a part of a page differently. Surrogate ESI header need to be send so esi tags are returned.
- [ ] **Level 7: Grace Keep Mode** (a request to a cached page which did expire still returns the cache page but the cache is refreshed in background, this means always fast responses to client) With `X/Y-Key` feature to just invalidate the cache but not remove it. [Varnish Grace Mode Reference](https://varnish-cache.org/docs/trunk/users-guide/vcl-grace.html) / [Varnish YKEY](https://docs.varnish-software.com/varnish-cache-plus/vmods/ykey/)
- [ ] **Level 8: User context Caching** (A endpoint is first trigger to get the user context which is used as cache context) so different security groups example can be cached. [FOSHttpCache User Context Caching](https://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html)

**Describe alternatives you've considered**

Using Varnish, Then sadly roadrunner can not longer use as SSL provider and requires a additional nginx in front of varnish handling SSL.

**Additional Context**

Multi Domain support should keep in mind. `example.org/test` is different to `example.com/test`.

Things which should be discussed. `File based` or in `memory cache` a hybrid solution would be great to be as fast as possible with low memory usage.

Static file response content don't need additional be stored in cache?

**Comment by rustatian** [comment]
Hey @alexander-schranz, sorry for the delay, got sick with covid in November 🚑 .
I am going to support at least Redis, boltdb, and in-memory (LRU, with configurable capacity) drivers for the cache in the first phase. The basic idea is to have a wrapper on the RR side that would work with any driver (Varnish, Redis, Postgresql (haha)) which you can easily configure via `.rr.yaml`.

**Comment by alexander-schranz** [comment]
@rustatian No problem, I hope you are fine and healthy again. Take your time what you need!
For varnish I think there is nothing required todo, as roadrunner would just need to forward the headers from the application correctly like it does it currently and purge request would directly go to varnish and not hit roadrunner in that scenario.
For built-in cache directly with roadrunner what I wanted to target in the proposal, redis sounds great as storage, with boltdb I'm not familiar - but seems something similar. A filebased cache would also something which would be great to work out of the box without additonal service then roadrunner. At the end I think the storage should just be abstracted so we can add additional in the future, we just make sure that the abstraction supports correclty the above scenarios based on http standard headers and common practices listed. The storage required to cache the content + response headers. Also we should make sure to set/calculate the correct [`Age`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age) response header when loaded from the cache to response how old the entry is. I forget that one, added above for completeness. So we need response content, response headers and the time when the entry was cached. 

At the end I just thought it would be a great addition to have a builtin http cache directly in roadrunner to make usage of the SSL feature in our applications which requires such a cache.  Still make sure you are doing fine, no stress on this one, work on it when you like it and don't forget to enjoy other things! For any questions or if I can test or provide you something just ping me here, happy to help if I can.

**Comment by rustatian** [comment]
>  I hope you are fine and healthy again.

Yeah, everything is good now, thanks 😃 

> A filebased cache would also something which would be great to work out of the box without additonal service then roadrunner.

BoltDB is a file-based cache. This is a sqlite3 analog. So, no configuration from the user end, just specify the driver and run. Much like the memory driver, but persist between RR restarts :)

> For any questions or if I can test or provide you something just ping me here, happy to help if I can.

Great, thank you very much.

If you don't mind, I'll mark this ticket as an implementation tracking ticket (thank you one more time for the good and detailed request) and it'll be open till the last level is implemented. For the RR 2.7 (middle of Jan) I'll implement `Level 1`, and will add 1-2 levels per RR version just to make sure that everything goes smoothly and w/o bugs. So you and the community would have the ability to seamlessly integrate the cache into the existing ecosystem.

**Comment by rustatian** [comment]
CI closed the issue by mistake 🦡

**Comment by alexander-schranz** [comment]
@rustatian Really nice to see that you had some time to implement a first version. 🎉

**Comment by rustatian** [comment]
You are very welcome 😃 
It'll take some time to implement the whole `RFC-7234` and add new drivers (Varnish, BoltDB, etc), but, we won't stop, I promise 🧑‍🏭
